# Generated by Django 2.2.6 on 2019-11-12 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0012_auto_20191112_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(auto_created=True, default=None, max_length=64, unique=True)),
                ('uuid', models.CharField(auto_created=True, default=uuid.UUID('9738e902-0525-11ea-9efa-24f6770d0683'), max_length=64, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Line', verbose_name='产品线')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Project', verbose_name='项目')),
            ],
        ),
    ]
