# Generated by Django 2.2.6 on 2019-11-12 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20191112_1623'),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(auto_created=True, default=None, max_length=64, unique=True)),
                ('uuid', models.CharField(auto_created=True, default=uuid.UUID('abadbb5c-0525-11ea-ad7e-24f6770d0683'), max_length=64, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Line', verbose_name='产品线')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Project', verbose_name='项目')),
            ],
        ),
        migrations.DeleteModel(
            name='DeployForm',
        ),
    ]
