# Generated by Django 2.2.6 on 2019-11-12 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20191112_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='cluster',
            field=models.CharField(auto_created=True, default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('bf0d4e7f-052a-11ea-af23-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
