# Generated by Django 2.2.6 on 2019-11-12 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20191112_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('3b15a563-052b-11ea-a573-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
