# Generated by Django 2.2.6 on 2019-11-12 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20191112_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('f2a598d4-44b7-446e-8bca-83319af3c279'), max_length=64, unique=True),
        ),
    ]
