# Generated by Django 2.2.6 on 2019-11-12 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20191112_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploy',
            options={'verbose_name': '部署', 'verbose_name_plural': '部署'},
        ),
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('d8f533d4-052e-11ea-b802-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
