# Generated by Django 2.2.6 on 2019-11-12 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20191112_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('999f1eda-0537-11ea-bbbb-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
