# Generated by Django 2.2.6 on 2019-11-12 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_auto_20191112_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('cdfc8b7f-0537-11ea-811c-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
