# Generated by Django 2.2.6 on 2019-11-13 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20191112_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('9b32fde8-05f1-11ea-a487-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
