# Generated by Django 2.2.6 on 2019-11-13 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20191113_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('58d12bbe-05f2-11ea-aff9-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
