# Generated by Django 2.2.6 on 2019-10-17 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c6d57030-f0a6-11e9-83ac-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
