# Generated by Django 2.2.6 on 2019-10-17 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191017_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('eeeffef4-f0a8-11e9-b825-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
