# Generated by Django 2.2.6 on 2019-10-17 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191017_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('41f07d4c-f0af-11e9-b3c4-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
