# Generated by Django 2.2.6 on 2019-10-17 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191017_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f20250c2-f0af-11e9-9f91-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
