# Generated by Django 2.2.6 on 2019-10-17 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191017_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a45dee8a-f0bd-11e9-866d-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
