# Generated by Django 2.2.6 on 2019-10-22 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191017_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d5ab1db8-f498-11e9-901c-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
