# Generated by Django 2.2.6 on 2019-10-22 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191022_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7415a808-f49b-11e9-a95c-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
