# Generated by Django 2.2.6 on 2019-10-22 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191022_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('91a3b23a-f49b-11e9-8edc-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
