# Generated by Django 2.2.6 on 2019-10-22 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191022_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b1b9a66e-f49b-11e9-9b91-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
