# Generated by Django 2.2.6 on 2019-10-22 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191022_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('34f58e46-f49c-11e9-ac6f-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
