# Generated by Django 2.2.6 on 2019-10-22 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191022_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('54fb434a-f49c-11e9-a41d-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
