# Generated by Django 2.2.6 on 2019-10-22 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191022_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('6df728f4-f49c-11e9-a517-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
