# Generated by Django 2.2.6 on 2019-11-06 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191106_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7c1a171e-0058-11ea-a73e-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
