# Generated by Django 2.2.6 on 2019-11-07 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191106_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ea708014-0138-11ea-8a11-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
