# Generated by Django 2.2.6 on 2019-11-12 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191112_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('973425de-0525-11ea-b99c-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
