# Generated by Django 2.2.6 on 2019-11-12 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20191112_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d8f06f50-052e-11ea-b5c8-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
