# Generated by Django 2.2.6 on 2019-11-12 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20191112_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b580475a-052f-11ea-906a-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
