# Generated by Django 2.2.6 on 2019-11-12 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20191112_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('999a5a52-0537-11ea-8e06-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
