# Generated by Django 2.2.6 on 2019-11-12 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20191112_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cdfa2936-0537-11ea-8e4e-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
