# Generated by Django 2.2.6 on 2019-11-13 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20191113_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('58cc6736-05f2-11ea-ade5-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
