# Generated by Django 2.2.6 on 2019-11-13 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20191113_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f05aa6ca-05f2-11ea-a8e7-24f6770d0683'), max_length=64, unique=True),
        ),
    ]
